name: Trend Tracker

on:
  # schedule:
  #   - cron: '0 7-23/3 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  track-trends:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Write Firebase credentials to file
      run: echo "$SERVICE_ACCOUNT_KEY" > service_account_key.json
      env:
        SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    
    - name: Run trend tracker
      env:
        # Email configuration - set these in GitHub repository secrets
        GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: python main.py
